[package]
name = "image-stitch"
version = "0.3.0"
authors = ["Comeza <aaron@geigr.io>"]
edition = "2018"

[dependencies]
image = "0.23.14"
clap = { git = "https://github.com/clap-rs/clap", features = ["derive"] }
alphanumeric-sort = "1.4.3"
