[package]
name = "cgutils"
version = "0.3.0"
authors = ["Comeza <aaron@geigr.dev>"]
edition = "2021"

[dependencies]
image = "0.23.14"
alphanumeric-sort = "1.4.3"
clap = { version = "4.1.4", features = ["derive"] }
thiserror = "2.0.3"
